# -*- coding: utf-8 -*-
"""contador_pdf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xGzuQh6p-naJejGShsUWqlOcVraJv23U
"""

!pip install PyPDF2

from google.colab import files

uploaded = files.upload()

from PyPDF2 import PdfReader

def leer_pdf(nombre_pdf):
    lector = PdfReader(nombre_pdf)
    texto = ""

    for pagina in lector.pages:
        contenido = pagina.extract_text()
        if contenido:
            texto += contenido.lower()

    return texto


def contar_palabra(texto, palabra):
    palabras = texto.split()
    return palabras.count(palabra.lower())


def contar_vocal(texto, vocal):
    return texto.count(vocal.lower())


def mostrar_matriz(matriz):
    print("\nMATRIZ DE RESULTADOS")
    print("-" * 35)
    for fila in matriz:
        print(fila)
    print("-" * 35)


# -------- PROGRAMA PRINCIPAL --------
nombre_pdf = input("Escribe el nombre del archivo PDF (ej: documento.pdf): ")
texto_pdf = leer_pdf(nombre_pdf)

resultados = [["Tipo", "objeto buscado", "Cantidad"]]

while True:
    print("\n¿Qué deseas contar?")
    print("1 - Una palabra")
    print("2 - Una vocal")
    print("3 - Mostrar matriz de resultados")
    print("4 - Salir")

    opcion = input("Selecciona una opción: ")

    if opcion == "1":
        palabra = input("Ingresa la palabra a buscar: ")
        cantidad = contar_palabra(texto_pdf, palabra)
        resultados.append(["Palabra", palabra, cantidad])
        print(f"La palabra '{palabra}' aparece {cantidad} veces.")

    elif opcion == "2":
        vocal = input("Ingresa una vocal (a, e, i, o, u): ").lower()
        if vocal in ["a", "e", "i", "o", "u"]:
            cantidad = contar_vocal(texto_pdf, vocal)
            resultados.append(["Vocal", vocal, cantidad])
            print(f"La vocal '{vocal}' aparece {cantidad} veces.")
        else:
            print("Error: vocal no válida.")

    elif opcion == "3":
        mostrar_matriz(resultados)

    elif opcion == "4":
        print("\nPrograma finalizado.")
        break

    else:
        print("Opción no válida.")